name: Latest blog post workflow
on:
  schedule:
    # Runs 11:04 every day
    - cron: '4 11 * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "http://feeds.feedburner.com/mattlacey"
